"""Add notification settings to clinics table

Revision ID: 08b75d419cd0
Revises: e04729c2b2e0
Create Date: 2025-10-28 14:13:39.029241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '08b75d419cd0'
down_revision: Union[str, None] = 'e04729c2b2e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add reminder_hours_before column as nullable first (SQLite requirement)
    op.add_column('clinics', sa.Column('reminder_hours_before', sa.Integer(), nullable=True))

    # Update existing rows with default value
    op.execute("UPDATE clinics SET reminder_hours_before = 24 WHERE reminder_hours_before IS NULL")

    # Make column NOT NULL
    with op.batch_alter_table('clinics') as batch_op:
        batch_op.alter_column('reminder_hours_before', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinics', 'reminder_hours_before')
    # ### end Alembic commands ###
