"""Add HMAC key field to refresh tokens for optimized lookups

Revision ID: 11946888e740
Revises: auth_schema_migration
Create Date: 2025-10-22 08:22:43.489564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '11946888e740'
down_revision: Union[str, None] = 'auth_schema_migration'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('hmac_key', sa.String(length=64), nullable=True))
    op.create_index('idx_refresh_tokens_hmac_key', 'refresh_tokens', ['hmac_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_refresh_tokens_hmac_key', table_name='refresh_tokens')
    op.drop_column('refresh_tokens', 'hmac_key')
    # ### end Alembic commands ###
