/**
 * Medical Record Template and Record types
 */

export type TemplateFieldType = 
  | 'text' 
  | 'textarea' 
  | 'number' 
  | 'date' 
  | 'dropdown' 
  | 'radio' 
  | 'checkbox';

export interface TemplateField {
  id: string; // UUID generated by backend
  label: string;
  type: TemplateFieldType;
  required: boolean;
  placeholder?: string | undefined;
  options?: string[] | undefined;
  order: number;
}

export interface MedicalRecordTemplate {
  id: number;
  clinic_id: number;
  name: string;
  description?: string;
  fields: TemplateField[];
  version: number;
  is_deleted: boolean;
  deleted_at?: string;
  created_at: string;
  created_by_user_id?: number;
  updated_at?: string;
  updated_by_user_id?: number;
}

export interface MedicalRecordTemplateCreateRequest {
  name: string;
  description?: string | undefined;
  fields: Omit<TemplateField, 'id'>[]; // Frontend doesn't provide IDs
}

export interface MedicalRecordTemplateUpdateRequest {
  version: number;
  name?: string | undefined;
  description?: string | undefined;
  fields?: TemplateField[]; // Must include existing IDs for persistent fields
}

export interface MedicalRecordTemplatesListResponse {
  templates: MedicalRecordTemplate[];
  total: number;
}
