/**
 * Medical Record Template and Record types
 */

export type TemplateFieldType =
  | 'text'
  | 'textarea'
  | 'number'
  | 'date'
  | 'dropdown'
  | 'radio'
  | 'checkbox';

export type MedicalRecordTemplateType = 'medical_record' | 'patient_form';

export interface TemplateField {
  id: string; // UUID generated by backend
  label: string;
  type: TemplateFieldType;
  required: boolean;
  placeholder?: string | undefined;
  description?: string | undefined;
  options?: string[] | undefined;
  order: number;
}

export interface MedicalRecordTemplate {
  id: number;
  clinic_id: number;
  name: string;
  template_type: MedicalRecordTemplateType;
  max_photos: number;
  description?: string;
  fields: TemplateField[];
  version: number;
  is_deleted: boolean;
  deleted_at?: string;
  created_at: string;
  created_by_user_id?: number;
  updated_at?: string;
  updated_by_user_id?: number;
}

export interface MedicalRecordTemplateCreateRequest {
  name: string;
  template_type?: MedicalRecordTemplateType;
  max_photos?: number;
  description?: string | undefined;
  fields: Omit<TemplateField, 'id'>[]; // Frontend doesn't provide IDs
}

export interface MedicalRecordTemplateUpdateRequest {
  version: number;
  name?: string | undefined;
  max_photos?: number;
  description?: string | undefined;
  fields?: TemplateField[]; // Must include existing IDs for persistent fields
}

export interface MedicalRecordTemplatesListResponse {
  templates: MedicalRecordTemplate[];
  total: number;
}

// Patient Photo types (matches backend PatientPhotoResponse)
export interface PatientPhoto {
  id: number;
  clinic_id: number;
  patient_id: number;
  medical_record_id?: number;
  uploaded_by_patient_id?: number;
  filename: string;
  content_type: string;
  size_bytes: number;
  description?: string;
  is_pending: boolean;
  created_at: string;
  url?: string;
  thumbnail_url?: string;
}

export interface PatientPhotosListResponse {
  items: PatientPhoto[];
  total: number;
}

// Medical Record types
export interface MedicalRecord {
  id: number;
  clinic_id: number;
  patient_id: number;
  template_id: number;
  appointment_id?: number;
  template_snapshot: {
    name: string;
    fields: TemplateField[];
  };
  values: Record<string, any>;
  source_type: 'clinic' | 'patient';
  patient_form_request_id?: number;
  last_updated_by_user_id?: number;
  last_updated_by_patient_id?: number;
  version: number;
  is_deleted: boolean;
  deleted_at?: string;
  created_at: string;
  created_by_user_id?: number;
  updated_at?: string;
  updated_by_user_id?: number;
  photos?: PatientPhoto[]; // Photos attached to this record

  // Enriched fields from backend
  appointment?: {
    id: number;
    start_time: string;
    end_time: string;
    appointment_type_name: string | null;
  };
  created_by_user_name?: string;
  updated_by_user_name?: string;
}

export interface MedicalRecordCreateRequest {
  template_id: number;
  appointment_id?: number;
  values: Record<string, any>;
  photo_ids?: number[];
}

export interface MedicalRecordUpdateRequest {
  version: number;
  values?: Record<string, any>;
  appointment_id?: number | null;
  photo_ids?: number[];
}

export interface MedicalRecordsListResponse {
  records: MedicalRecord[];
  total: number;
}

export interface PatientFormSetting {
  id: number;
  clinic_id: number;
  appointment_type_id: number;
  template_id: number;
  timing_mode: 'immediate' | 'hours_after' | 'specific_time';
  hours_after?: number | null;
  days_after?: number | null;
  time_of_day?: string | null;
  message_template: string;
  flex_button_text: string;
  notify_admin: boolean;
  notify_appointment_practitioner: boolean;
  notify_assigned_practitioner: boolean;
  is_enabled: boolean;
  display_order: number;
  created_at: string;
  updated_at: string;
}

export interface PatientFormRequest {
  id: number;
  clinic_id: number;
  patient_id: number;
  template_id: number;
  appointment_id?: number | null;
  request_source: 'auto' | 'manual';
  patient_form_setting_id?: number | null;
  notify_admin: boolean;
  notify_appointment_practitioner: boolean;
  notify_assigned_practitioner: boolean;
  status: 'pending' | 'submitted' | 'skipped';
  access_token: string;
  medical_record_id?: number | null;
  sent_at: string;
  submitted_at?: string | null;
  created_at: string;
  updated_at: string;
  // Enriched
  template_name?: string;
}

export interface PatientPhotoUpdateRequest {
  description?: string;
  medical_record_id?: number;
}
